first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
full_name = first_name.upper() + " " + last_name.upper()
birth_year = input("What year were you born? ")
hobby = input("Enter your favorite hobby: ")
age = 2026 - int(birth_year)
width = 36
print("=" * width)
print("   USER PROFILE CARD   ".center(width))
print("=" * width)
print(f"Name:\t{full_name:>{width-8}}") 
print(f"Age:\t{age:>{width-8}}")
print(f"Hobby:\t{hobby:>{width-8}}")
print("-" * width)
print("Thank you for creating your profile!")
print("=" * width)