#coding problem 1
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
full_name = first_name.upper() + " " + last_name.upper()
birth_year = input("What year were you born? ")
hobby = input("Enter your favorite hobby: ")
age = 2026 - int(birth_year)
width = 36
print("=" * width)
print("   USER PROFILE CARD   ".center(width))
print("=" * width)
print(f"Name:\t{full_name:>{width-8}}") 
print(f"Age:\t{age:>{width-8}}")
print(f"Hobby:\t{hobby:>{width-8}}")
print("-" * width)
print("Thank you for creating your profile!")
print("=" * width)

# coding problem 2
sentence = input("Enter a sentence: ")
total_length = len(sentence)
short_length = len(sentence.replace(" ", ""))
word_count = len(sentence.split())
vowel_count = sum(1 for char in sentence.lower() if char in 'aeiou')
upper_sentence = sentence.upper()
lower_sentence = sentence.lower()
reversed_sentence = sentence[::-1]

print("\n====== Sentence Analysis ======".center(36) + "\n")
print(f"Entered Sentence: {sentence}\n")
print("--- Analysis Results ---".center(36))
print(f"Sentence Length (with spaces): {total_length}")
print(f"Sentence Length (excluding spaces): {short_length}")
print(f"Word Count: {word_count}")
print(f"Vowel Count: {vowel_count}")
print(f"Uppercase: {upper_sentence}")
print(f"Lowercase: {lower_sentence}")
print(f"Reversed: {reversed_sentence}")
print(f"Starts with capital letter: {bool(sentence[0].isupper())}")
print(f"Ends with punctuation: {bool(sentence.endswith(('.', '!', '?')))}")

